adding makefile for separate builds
racker/Minerva pull request #155
Opened 2020-09-14 14:36 UTC by lovedeep92

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-565

**Description:**

1) Create makefile - a file which is used for creating multiple builds using make inbuilt automation tool in CLI
2) create two build folders with name Minerva and Admin inside Dist folder.

**Testing:**

`npm run test:unit`

 ## Screenshots:
(if applicable)

2020-09-14 14:57 UTC, FarajiA commented
Ok this looks good, where is the output location though, can we configure that?

2020-09-14 15:43 UTC, FarajiA commented on projects/admin/src/app/app.module.ts
>     // SharedModule
We can remove.

2020-09-14 15:52 UTC, FarajiA requested changes
Ok just saw your Jira update that answers my questions from above:

> After that we have one single command which will create two separate folders inside dist/
i.e: dist/admin and dist/minerva

Can you add build instructions in the _README_ and then add NPM scripts to execute this? I don't think our current build process in NPM reflects this.

2020-09-14 16:41 UTC, lovedeep92 commented on projects/admin/src/app/app.module.ts
>     // SharedModule
done !!

2020-09-14 18:00 UTC, lovedeep92 commented
@FarajiA , yup and its done!!

2020-09-15 14:11 UTC, FarajiA approved these changes
LGTM

2020-09-15 14:22 UTC, merged