Del multiple resources mnrva 577
racker/Minerva pull request #162
Opened 2020-09-23 13:46 UTC by lovedeep92

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-577

**Description:**

1) Create new modal for showing success message If resource is deleted and error if 404 and other issue occurred during deleting resource.

2) Use promiseAll for deleting multiple resources and check which one failed and which on being succeeded.

**Testing:**
`
npm run test:unit`

**Screenshots:
![Sep-23-2020 19-16-12](https://user-images.githubusercontent.com/66314110/94021106-48d2fb00-fdd1-11ea-8966-3ab2358e2212.gif)
**
(if applicable)

2020-09-23 18:24 UTC, FarajiA commented on src/app/_services/resources/resources.service.ts
> +  } // deleteMultipleResources
You can remove the comment line here, and add a JS Comment to this function.

2020-09-23 18:45 UTC, FarajiA requested changes
This is coming along nicely you're gonna want to merge the latest from `devel` branch and resolve your conflicting files.

2020-09-23 18:45 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.scss
> +    color: #32D190;
So for the colors used in the success & error, we may have never gone over this but I try to use the green and reds from Helix library - this is very minor and a low priority but in the Helix alert & other components you can view the color schemes they're using https://helixdesignsystem.github.io/helix-ui/components/alert

2020-09-23 18:45 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  triggerClose(flag) {
I'm not seeing any tests for `triggerOk`, `triggerClose` & `triggerConfirm`

2020-09-24 06:56 UTC, pras7430 reviewed
the triggerConfirm function needs some changes

2020-09-24 06:56 UTC, pras7430 commented on src/app/_services/resources/resources.service.spec.ts
> +    it('should delete a multiple Resource', () => {
this test case doesn't seem to be correct, as we don't have mock service for the same.. so it will throw 404 in such cases.

2020-09-24 06:56 UTC, pras7430 commented on src/app/_services/resources/resources.service.ts
> +
we need to add a mock response here too.

2020-09-24 06:56 UTC, pras7430 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +    this.modalType = 'delResourceModal';
can we set its value at the place of its declaration?

2020-09-24 11:54 UTC, lovedeep92 commented on src/app/_services/resources/resources.service.ts
> +  } // deleteMultipleResources
done!!

2020-09-24 12:02 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.scss
> +    color: #32D190;
Yup .. right .. will go with consistency!!

2020-09-24 12:04 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +    this.modalType = 'delResourceModal';
Yup .. done !!

2020-09-24 16:05 UTC, lovedeep92 commented on src/app/_services/resources/resources.service.spec.ts
> +    it('should delete a multiple Resource', () => {
done !!

2020-09-24 16:05 UTC, lovedeep92 commented on src/app/_services/resources/resources.service.ts
> +
done!!

2020-09-24 16:21 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  triggerClose(flag) {
tirggerOk, triggerClose are done and working on triggerConfirm!

2020-09-24 17:23 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  triggerClose(flag) {
DONE!!

2020-09-25 13:17 UTC, pras7430 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  triggerConfirm() {
1. we can split into two different functions.
2. Let d=0 can be replaced with i.
3.  this.resourceArr,this.confirmMessageError,this.confirmMessageSuccess etc  values should be reset.

2020-09-25 13:58 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  triggerConfirm() {
DONE

2020-09-25 16:52 UTC, FarajiA approved these changes

2020-09-28 19:00 UTC, merged