Bug mnrva 592
racker/Minerva pull request #168
Opened 2020-10-07 14:32 UTC by lovedeep92

## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-592

**Description:**
Fixed bugs.
Add test cases for functions.

**Testing:**

`npm run test:unit`

 ## Screenshots:
(if applicable)

2020-10-07 15:42 UTC, pras7430 approved these changes
I have pushed a change

2020-10-07 15:42 UTC, pras7430 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
> +    component.monitors.forEach(e => {
this does not seem valid. Use the reset function to set e.checked values with false

2020-10-07 15:42 UTC, pras7430 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
>      count++;
assign a value to count here else it may be NAN.

2020-10-07 15:42 UTC, pras7430 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
>      count++;
assign a value to count here else it may be NAN.

2020-10-07 15:56 UTC, lovedeep92 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
>      count++;
DONE

2020-10-07 15:56 UTC, lovedeep92 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
>      count++;
DONE

2020-10-07 16:04 UTC, lovedeep92 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
> +    component.monitors.forEach(e => {
DONE. please check

2020-10-07 17:23 UTC, FarajiA requested changes

2020-10-07 17:23 UTC, FarajiA commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
> +  fit('should execute reset for checked flag to false', () => {
You want to remove _fit_

2020-10-07 17:23 UTC, FarajiA commented on src/app/_features/monitors/components/list/monitorslist.component.html
> +        {{selectedMonitor.monitor.name || monitorUtil.formatSummaryField(selectedMonitor.monitor)}}
Nice

2020-10-07 17:28 UTC, lovedeep92 commented on src/app/_features/monitors/components/list/monitorslist.component.spec.ts
> +  fit('should execute reset for checked flag to false', () => {
my bad .. anyways its done !

2020-10-08 18:14 UTC, FarajiA approved these changes
+1

2020-10-12 12:06 UTC, merged