Proxy conf ii mnrva 605
racker/Minerva pull request #178
Opened 2020-11-04 00:21 UTC by FarajiA

## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-605
Blocking: https://jira.rax.io/browse/MNRVA-603

 ## Description:
This is an update that will completely remove the `localenv` folder, and proxy all requests from the app to portal app. When setting up the app we will have the choice to decide whether to use the _staging_ or _prod_ version of identity & portal. 

 ## Testing:
`npm run start:dev`

 ## Screenshots:
![proxyLogin](https://user-images.githubusercontent.com/5041718/98054738-65674780-1e01-11eb-9ff7-9d087ffb4307.gif)

2020-11-05 15:03 UTC, lovedeep92 reviewed
Hey, I am getting **"An unhandled exception occurred: Script file scripts/portaldata.js does not exist."** when running `**npm run start:dev**`

2020-11-05 15:30 UTC, pras7430 reviewed
"npm run start:dev" script showing me below error. 

An unhandled exception occurred: Script file scripts/portaldata.js does not exist.

2020-11-05 15:30 UTC, pras7430 commented on angular.json
> +                "scripts/portaldata.js",
hey, do we have a scripts folder?

2020-11-10 17:17 UTC, pras7430 requested changes
fine!

2020-11-11 14:35 UTC, FarajiA commented on angular.json
> +                "scripts/portaldata.js",
This is autogenerated

2020-11-11 15:11 UTC, pras7430 approved these changes

2020-11-17 15:07 UTC, merged