Sorting Resources
racker/Minerva pull request #179
Opened 2020-11-04 16:05 UTC by lovedeep92

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-608

**Description:**

Resources page has the ability to sort.

Added sorting by resource id.

**Testing:**

`npm run test:unit`

 ## Screenshots:
(if applicable)

2020-11-04 19:11 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.spec.ts
> +  fit('should execute delete multiple resources failed', () => {
Remove _fit_

2020-11-04 19:12 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.spec.ts
> +  fit('should check sorting resources desc', () => {
_fit_ here

2020-11-04 19:25 UTC, FarajiA requested changes

2020-11-04 19:25 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +          console.log("this.resourceService.resources.content ", JSON.stringify(this.resourceService.resources.content));
We can remove this log

2020-11-04 19:25 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.html
> +          <hx-icon *ngIf="isDescending"
Can we make these `<hx-icon>` elements have the hand pointer when hovered over? CSS would be something like `cursor: pointer`.

2020-11-04 19:25 UTC, FarajiA commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  sortResources(orderBy, sortBy) {
Since this has params and uses other functions let's add comments.

2020-11-05 11:45 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.html
> +          <hx-icon *ngIf="isDescending"
done !!

2020-11-05 11:45 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +          console.log("this.resourceService.resources.content ", JSON.stringify(this.resourceService.resources.content));
done!!

2020-11-05 11:45 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.spec.ts
> +  fit('should check sorting resources desc', () => {
done!!

2020-11-05 11:46 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.spec.ts
> +  fit('should execute delete multiple resources failed', () => {
done!!

2020-11-05 11:46 UTC, lovedeep92 commented on src/app/_features/resources/components/list/resourceslist.component.ts
> +  sortResources(orderBy, sortBy) {
done!!

2020-11-06 08:50 UTC, FarajiA approved these changes

2020-11-06 15:58 UTC, merged