Display error responses given from Salus API
racker/Minerva pull request #205
Opened 2021-01-18 16:24 UTC by lovedeep92

JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-641

**Description:**

Create an interface and catch the exception and logs it to the browser on client side.

**Testing:**

`npm run start:unit`

Screenshots:
(if applicable)

2021-01-19 05:59 UTC, FarajiA commented on src/app/_services/logging/logging.service.ts
> +  handleError(error: SalusError){
So for this function it would help if the name specified what's happening. Salus should be in the title maybe `salusLog` or `salusError`.

2021-01-19 06:16 UTC, FarajiA commented on src/app/_services/logging/logging.service.ts
> +    console.log({ level: LogLevels.info, error: error.error });
This functionality would have added benefit if it were to execute the `log` method in this same class instead of using the console log here. This way we could pass a message along to the alert component also for the user.  

It would also be great for us to see the entire object listed in the console. I do see there's a `throwError` and this prints to console. Essentially this is printing twice to the console I would think?

2021-01-19 06:23 UTC, FarajiA commented on src/app/_services/logging/logging.service.ts
> +    console.log({ level: LogLevels.info, error: error.error });
`LogLevels.error` should also be the enum used.

2021-01-19 06:27 UTC, FarajiA requested changes
I think the two changes mentioned above should be the focus:
 - there should be only one function here doing the console logging
 - change the LogLevel to error

2021-01-19 12:02 UTC, pras7430 commented on src/app/_services/monitors/monitor.service.ts
> +            catchError(this.logService.handleError)
Global level error handler will catch client and server errors.

2021-01-19 12:02 UTC, pras7430 commented on src/app/_services/logging/logging.service.ts
> +  handleError(error: SalusError){
Global Error handler has the same name function and it gets automatic invocation(if I am not wrong) while any exception and we can use that.

2021-01-19 15:46 UTC, FarajiA commented on src/app/_services/logging/logging.service.ts
> +  handleError(error: SalusError){
@pras7430 yes that's a pretty good option. It may however be difficult to isolate only Salus response errors but yes, that Global Error handler gets invoked anytime of http request error.

2021-01-20 16:32 UTC, lovedeep92 commented
I have made it so that we do not need an interface for the same and it works fine on different scenarios.

2021-01-20 17:26 UTC, FarajiA commented on src/app/_services/monitors/monitor.service.ts
> +import { tap, delay, catchError } from 'rxjs/operators';
Looks like catchError isn't used?

2021-01-20 17:39 UTC, lovedeep92 commented on src/app/_services/monitors/monitor.service.ts
> +import { tap, delay, catchError } from 'rxjs/operators';
yes its not!
We will be handling it using global error handler. only one thing we removed is handling error on component so that it goes to global error handler file and we could modify the error in error.service.ts file.

2021-01-21 15:10 UTC, lovedeep92 commented
Hey @FarajiA ,

I have update the e2e test cases for the same PR

2021-01-22 05:27 UTC, FarajiA approved these changes

2021-01-22 11:49 UTC, lovedeep92 commented on src/app/_features/monitors/pages/create/monitor-create.page.ts
> +      }/*, (error) => {
@FarajiA , It was removed before you made the changes. I will revert it back.

2021-01-22 11:49 UTC, lovedeep92 commented on src/app/_services/error.service.spec.ts
> +    expect(error.status).toEqual(400);
Okay .. I'll update the same.

2021-01-22 11:59 UTC, lovedeep92 commented on src/app/_features/monitors/pages/create/monitor-create.page.ts
> +      }/*, (error) => {
@FarajiA , you made the changes and I am not getting it. You have added the pipe in place of subscribe. Please check one more time.

2021-01-22 16:19 UTC, lovedeep92 commented
@FarajiA , I have update the test case. Please check when you get a chance!

2021-01-25 17:42 UTC, lovedeep92 commented
@FarajiA , Can I merge this PR? I think you are done with the fixes?

2021-01-27 21:29 UTC, merged