Selection tags mnrva 786
racker/Minerva pull request #236
Opened 2021-06-07 16:40 UTC by pras7430

## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-786

 ## Description:
1. Tag dropdown added to left nav
2.  Test cases and changed

 ## Testing:

 ## Screenshots:
(if applicable)

2021-06-07 22:32 UTC, FarajiA commented on src/app/_features/visualize/components/selectNav/metric-group/metric-dropdown.component.spec.ts
> +  it('should add drown down create', () => {
These 3 tests have all the same `it` statement but I can see they test different functionality.

2021-06-07 22:34 UTC, FarajiA commented on src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
> +  it("should change metrics", () =>{
Same here. These `it` statements are identical

2021-06-07 22:45 UTC, FarajiA requested changes
Looks like we'll have to see why the GCP Build is failing.

2021-06-07 22:45 UTC, FarajiA commented on src/app/_mocks/metrics/metrics.json
> +        "monitoring_system": "ZENOSS",
For these let's not use real Acct numbers, device numbers or UUID numbers.

2021-06-07 22:45 UTC, FarajiA commented on src/app/_services/metrics/metrics.service.ts
> +    return this.http.get<[string]>(`${this.metricsURL}/metadata/metricNames`,{ headers:httpOptions.headers,
This should be `string[]`?

2021-06-07 22:45 UTC, FarajiA commented on src/app/_services/metrics/metrics.service.ts
> +    return this.http.get<[string]>(`${this.metricsURL}/metadata/tags`,{ headers:httpOptions.headers,
`string[]`?

2021-06-07 22:45 UTC, FarajiA commented on src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
> +  /*===============================DropDown change event========================*/
Nice. I like the /*==========*/ for code sections. I'll do the same

2021-06-07 22:45 UTC, FarajiA commented on src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
> +    //this.getlistOfMetric(changedGroup);
We can remove.

2021-06-08 21:25 UTC, FarajiA approved these changes

2021-06-09 13:34 UTC, lovedeep92 commented on package.json
> +    "test:e2e-ci": "webdriver-manager update --standalone false --gecko false --versions.chrome 91.0.4472.77 && ng e2e --project=minerva -c=mock",
package.json changes not need to be added to devel I think!

2021-06-09 13:35 UTC, lovedeep92 commented on src/app/_features/visualize/components/selectNav/metric-group/metric-dropdown.component.ts
> +    if (!!this.defalutSelection && this.defalutSelection === item)
it should be default, not defalut !!

2021-06-09 16:29 UTC, merged